# Site settings
title: "CS373 Fall 2017: Taylor Kline"
email: taylor.kline@utexas.edu
description: > # this means to ignore newlines in this block
   Software Engineering in Python
# used for the canonical header and for the RSS link
url: https://jkdf2.github.io
baseurl: /swe-blog

#removing any of this will omit the relevant HTML
#to add more SVGs, see: http://codepen.io/ruandre/pen/howFi
github_username: jkdf2
facebook_username: taylor.kline.me
linkedin_username: taylorckline

timezone: America/Chicago
encoding: utf-8

gems:
     - jekyll-sitemap
     - jekyll-feed

exclude: [TODO.txt, Gemfile*, README.md]
permalink:
   /:categories/:title/
