# Site settings
title: CS371p Fall 2016: Taylor Kline
email: Taylor.Kline@utexas.edu
description: > # this means to ignore newlines in this block
   Object Oriented Programming in C++
# used for the canonical header and for the RSS link
url: https://oop-blog-taylor.github.io
baseurl: /oop-blog

#removing any of this will omit the relevant HTML
#to add more SVGs, see: http://codepen.io/ruandre/pen/howFi
github_username: jkdf2
facebook_username: taylor.kline.me
linkedin_username: taylorckline

timezone: America/Chicago
encoding: utf-8

gems:
     - jekyll-sitemap
     - jekyll-feed

exclude: [TODO.txt, Gemfile*, README.md]
permalink:
   /:categories/:title/
